#! /bin/sh
#
# Script for usb-gadget
#
# Clancor Technovates

CONF_FILE="/etc/default/usb-gadget.conf"
cp /etc/dnsserver /etc/resolv.conf

die() {
        echo "ERROR: $1"
        exit 1
}

go() {
        test -e "$CONF_FILE" && . "$CONF_FILE" 

        case "$USB_MODE" in
        networking)     setup_usb g_ether ;;
        storage)        setup_usb g_file_storage "$MODULE_OPTIONS" ;;
        serial)         setup_usb g_serial ;;
        hostmode)       unload_usb_gadgets
                        setup_usb ohci_hcd "$MODULE_OPTIONS" ;;
        none)           unload_usb_gadgets ;;
        esac

}

setup_usb() {

        if ! ( lsmod | grep -q "$1" )
        then
                unload_usb_gadgets
                echo "Loading [$1]"
                modprobe "$1" "$MODULE_OPTIONS"
	if [ "$1" == "g_serial" ]
                then
                /sbin/getty -L /dev/ttyGS0 115200 vt100 & 
                echo "Getty initialized successfully"
                fi
	else
                echo "Already loaded: [$1]"
        fi
}

unload_usb_gadgets() {
        KERNEL_VERSION="`uname -r`"
        GADGET_MODULES="`find /lib/modules/$KERNEL_VERSION/kernel/drivers/usb/gadget -name "*g_*"`"

        for module in $GADGET_MODULES
        do
                MODULE_NAME="`basename $module | sed "s/\.ko//"`"

                if ( lsmod | grep -q "$MODULE_NAME" )
                then
                        echo "Unloading [$MODULE_NAME]"
                        rmmod "$module"
                fi
        done
}

go

